"""Add password_hash to User model

Revision ID: 19b5d9a18fb2
Revises: ba0f0be78595
Create Date: 2024-07-16 15:20:15.837129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19b5d9a18fb2'
down_revision = 'ba0f0be78595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('priority',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=32),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=256),
               type_=mysql.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
