"""Initial migration

Revision ID: ba0f0be78595
Revises: 
Create Date: 2024-07-16 15:19:12.775550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba0f0be78595'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('priority',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=64),
               nullable=False)
        batch_op.alter_column('due_date',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
